### ISSUE TITLE
getWebsocketHandshakeProcess should use second !

### ISSUE THREAD

**Issue by vygr** [akinaru/websocket-non-blocking-cpp#1]
Hi, looking at websockethandshake::getWebsocketHandshakeProcess, should it not be testing the value string with it->second ? The key is it->first the value is it->second ?

Regards

Chris

**Comment by bertrandmartel** [comment]
Hi, thank you I've updated websocket handshake [here](https://github.com/akinaru/websocket-non-blocking-cpp/blob/master/libwebsocket/protocol/websocket/websockethandshake.cpp#L57-L59)
